#!/bin/env bash

# https://github.com/linuxdeploy/linuxdeploy/issues/272
export NO_STRIP=true

# Конфиг
APP=ffmpeg
BINARY_PATH="$(which $APP)"
APPDIR=./ffmpeg.AppDir
ICON_SOURCE=icon.png
ICON_NAME=$APP
CATEGORIES="AudioVideo"
