#!/bin/env bash

# https://github.com/linuxdeploy/linuxdeploy/issues/272
export NO_STRIP=true

# Конфиг
APP=go
BINARY_PATH="$(which $APP)"
APPDIR=./Go.AppDir
ICON_SOURCE=icon.png
ICON_NAME=$APP
CATEGORIES="Development"
