#!/bin/env bash

# https://github.com/linuxdeploy/linuxdeploy/issues/272
export NO_STRIP=true

# Конфиг
APP=cmake
APP_VERSION="3.31.8"
APPDIR=./Cmake.AppDir
ICON_SOURCE=icon.png
ICON_NAME=$APP
CATEGORIES="Development"
