#!/bin/env bash

# https://github.com/linuxdeploy/linuxdeploy/issues/272
export NO_STRIP=true

# Конфиг
readonly APP=cmake
readonly APP_VERSION="3.31.8"
readonly APPDIR=./${APP}.AppDir
readonly ICON_SOURCE=icon.png
readonly ICON_NAME=$APP
readonly CATEGORIES="Development;Building"
