#!/bin/env bash

# https://github.com/linuxdeploy/linuxdeploy/issues/272
export NO_STRIP=true

# Конфиг
APP=strace
BINARY_PATH="$(which $APP)"
APPDIR=./Strace.AppDir
ICON_SOURCE=icon.png
ICON_NAME=$APP
CATEGORIES="Development"
