#!/bin/env bash

set -euo pipefail

source "./conf"
source "$(dirname "$0")/lib/_customize"

print_info() {
  echo -e "${c_yellow}${1}${c_def}"
}
print_success() {
  echo -e "${c_green}${1}${c_def}"
}
print_error() {
  echo -e "${c_red}${1}${c_def}"
}

print_info "Check deps"
command -v magick >/dev/null && {
  print_success "[✓] ImageMagick: found"
} || {
  print_error "[-] ImageMagick (convert) not found"
  exit 1
}

command -v ../.././linuxdeploy >/dev/null && {
  print_success "[✓] linuxdeploy: found"
} || {
  print_error "linuxdeploy not found"
  exit 1
}

echo
print_info "Make dirs"
rm -rf "${APPDIR}" &&
  print_success "[✓] Remove ${APPDIR}"

mkdir -p "${APPDIR}/usr/bin" &&
  print_success "[✓] Make dir: ${APPDIR}/usr/bin"

mkdir -p "${APPDIR}/usr/share/applications" &&
  print_success "[✓] Make dir: ${APPDIR}/usr/share/applications"

mkdir -p "${APPDIR}/usr/share/icons/hicolor" &&
  print_success "[✓] Make dir: ${APPDIR}/usr/share/icons/hicolor"

echo
print_info "Add binary"
cp ${BINARY_PATH} "${APPDIR}/usr/bin/"

print_info "Add AppRun"
cat > "${APPDIR}/AppRun" <<EOF
#!/bin/bash
HERE=\$(dirname "\$(readlink -f "\$0")")
exec "\$HERE/usr/bin/${APP}" "\$@"
EOF
chmod +x "${APPDIR}/AppRun"

print_info "Add .desktop"
cat > "${APPDIR}/usr/share/applications/${APP}.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=${APP}
Exec=${APP}
Icon=${ICON_NAME}
Terminal=true
Categories=${CATEGORIES};
EOF

echo
print_info "Add icons"
for size in 16 32 64 128 256; do
  path="${APPDIR}/usr/share/icons/hicolor/${size}x${size}/apps"
  icon="${ICON_NAME}.png"
  mkdir -p "${path}"
  magick "${ICON_SOURCE}" -resize ${size}x${size} "${path}/${icon}" &&
    print_success "[✓] Icon convert: ${path}/${icon}"
done

echo
print_info "Build"
../.././linuxdeploy \
  --appdir "${APPDIR}" \
  --executable="${APPDIR}/usr/bin/${APP}" \
  --desktop-file="${APPDIR}/usr/share/applications/${APP}.desktop" \
  --icon-file="${APPDIR}/usr/share/icons/hicolor/256x256/apps/${ICON_NAME}.png" \
  --output appimage

echo
print_info "Move ${APP} to ../builds"
mkdir -p ../../builds/
mv "${APP}"*.AppImage ../../builds/${APP}
