#!/bin/env bash

set -euo pipefail

echo "Find and delete *.AppDir..."
find "apps" -type d -name '*.AppDir' -exec rm -rf {} +

echo "Find and delete *.AppImage файлов..."
find "apps" -type f -name '*.AppImage' -exec rm -f {} +

echo "Cleanup complete"
