#!/bin/env bash

# https://github.com/linuxdeploy/linuxdeploy/issues/272
export NO_STRIP=true

# Конфиг
readonly APP=git
readonly BINARY_PATH="$(which $APP)"
readonly APPDIR=./${APP}.AppDir
readonly ICON_SOURCE=icon.png
readonly ICON_NAME=$APP
readonly CATEGORIES="Development;RevisionControl"
